// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ukqeopyvuswgropblgdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrcWVvcHl2dXN3Z3JvcGJsZ2RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1MTg3ODgsImV4cCI6MjA3ODA5NDc4OH0.R6qn_VTimAyL9BYiRw8cXIBdl4S-cJrwIfJeZ6p8nks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);